language: go

go:
  - "1.9.x"
  - "1.10.x"

before_install:
  - go get -u golang.org/x/lint/golint

before_script:
  - go vet ./...
  - golint ./...

script:
  - go test -v ./...

notifications:
  email: false
